apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
      - name: html-container
        image: singuluridinesh007/myimg:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: html-app-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: html-app
